export const DEFAULT_HUGINN_CONFIG = Object.freeze({
	dataDir: ".pi/agent/huginn/db",
	embeddingModel: "nomic-ai/nomic-embed-text-v1.5",
	embeddingDim: 768,
	chunkSize: 512,
	chunkOverlap: 64,
	minChunkSize: 32,
	autoIngestion: true,
	ingestRoles: ["user", "assistant", "toolResult"],
	autoRetrieval: true,
	autoRetrievalMax: 5,
	minSimilarity: 0.6,
	reindexBatchSize: 32,
	extraIgnore: [],
	ignoreDotDirs: true,
	maxIndexedFiles: 200,
});

export const HARDCODED_EXCLUSIONS = Object.freeze([
	".git",
	".pi-lens",
	"node_modules",
	"target",
	".next",
	"dist",
	"package-lock.json",
	"yarn.lock",
	"pnpm-lock.yaml",
	"Cargo.lock",
	"poetry.lock",
	"Gemfile.lock",
]);
